# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Asus\Desktop\OptiVision\GUI\Register.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from os import path

class Ui_Register(object):
    def setupUi(self, OptiVision):
        base_dir = path.dirname(path.abspath(__file__))
        OptiVision.setObjectName("OptiVision")
        OptiVision.resize(852, 658)
        OptiVision.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(235, 255, 251);")
        self.centralwidget = QtWidgets.QWidget(OptiVision)
        self.centralwidget.setObjectName("centralwidget")
        self.Welcome_Label = QtWidgets.QLabel(self.centralwidget)
        self.Welcome_Label.setGeometry(QtCore.QRect(300, 0, 381, 101))
        font = QtGui.QFont()
        font.setFamily("Sitka Text Semibold")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.Welcome_Label.setFont(font)
        self.Welcome_Label.setObjectName("Welcome_Label")
        self.Email_Label = QtWidgets.QLabel(self.centralwidget)
        self.Email_Label.setGeometry(QtCore.QRect(391, 211, 56, 24))
        self.Email_Label.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Email_Label.setFont(font)
        self.Email_Label.setObjectName("Email_Label")
        self.Password_Label = QtWidgets.QLabel(self.centralwidget)
        self.Password_Label.setGeometry(QtCore.QRect(391, 294, 91, 24))
        self.Password_Label.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Password_Label.setFont(font)
        self.Password_Label.setObjectName("Password_Label")
        self.EmailEditBox = QtWidgets.QLineEdit(self.centralwidget)
        self.EmailEditBox.setGeometry(QtCore.QRect(390, 251, 221, 31))
        self.EmailEditBox.setAcceptDrops(True)
        self.EmailEditBox.setAutoFillBackground(False)
        self.EmailEditBox.setStyleSheet("QLineEdit{\n"
"    background: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"    border:1px solid\n"
"}\n"
"QLineEdit:focus{\n"
"    background: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"    border:1px solid #aa4f47\n"
"}\n"
"")
        self.EmailEditBox.setFrame(True)
        self.EmailEditBox.setClearButtonEnabled(False)
        self.EmailEditBox.setObjectName("EmailEditBox")
        self.Password1EditBox = QtWidgets.QLineEdit(self.centralwidget)
        self.Password1EditBox.setGeometry(QtCore.QRect(390, 340, 221, 31))
        self.Password1EditBox.setAcceptDrops(True)
        self.Password1EditBox.setAutoFillBackground(False)
        self.Password1EditBox.setStyleSheet("QLineEdit{\n"
"    background: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"    border:1px solid\n"
"}\n"
"QLineEdit:focus{\n"
"    background: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"    border:1px solid #aa4f47\n"
"}\n"
"")
        self.Password1EditBox.setFrame(True)
        self.Password1EditBox.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password1EditBox.setClearButtonEnabled(False)
        self.Password1EditBox.setObjectName("Password1EditBox")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(450, 210, 21, 16))
        self.label_5.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(480, 290, 21, 16))
        self.label_6.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_6.setObjectName("label_6")
        self.OptiVision_Image = QtWidgets.QLabel(self.centralwidget)
        self.OptiVision_Image.setGeometry(QtCore.QRect(10, 160, 221, 271))
        self.OptiVision_Image.setStyleSheet("background-color: rgb(246, 255, 225);")
        self.OptiVision_Image.setText("")
        Coloredpath=path.join(base_dir, "Colored.jpg")
        self.OptiVision_Image.setPixmap(QtGui.QPixmap(Coloredpath))
        self.OptiVision_Image.setScaledContents(True)
        self.OptiVision_Image.setObjectName("OptiVision_Image")
        self.RegisterButton = QtWidgets.QPushButton(self.centralwidget)
        self.RegisterButton.setGeometry(QtCore.QRect(430, 500, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RegisterButton.setFont(font)
        self.RegisterButton.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(246, 255, 225);\n"
"    border-radius:5px;\n"
"    border: 1px solid\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(237, 248, 255);\n"
"}\n"
"")
        RegisterIcon=path.join(base_dir, "RegisterIcon.png")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(RegisterIcon), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RegisterButton.setIcon(icon)
        self.RegisterButton.setIconSize(QtCore.QSize(18, 18))
        self.RegisterButton.setObjectName("RegisterButton")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(0, -20, 251, 781))
        self.label_9.setStyleSheet("background-color: rgb(246, 255, 225);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.Name_Label = QtWidgets.QLabel(self.centralwidget)
        self.Name_Label.setGeometry(QtCore.QRect(391, 130, 56, 24))
        self.Name_Label.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Name_Label.setFont(font)
        self.Name_Label.setObjectName("Name_Label")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(450, 129, 21, 16))
        self.label_10.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_10.setObjectName("label_10")
        self.NameEditBox = QtWidgets.QLineEdit(self.centralwidget)
        self.NameEditBox.setGeometry(QtCore.QRect(390, 170, 221, 31))
        self.NameEditBox.setAcceptDrops(True)
        self.NameEditBox.setAutoFillBackground(False)
        self.NameEditBox.setStyleSheet("QLineEdit{\n"
"    background: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"    border:1px solid\n"
"}\n"
"QLineEdit:focus{\n"
"    background: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"    border:1px solid #aa4f47\n"
"}\n"
"")
        self.NameEditBox.setFrame(True)
        self.NameEditBox.setClearButtonEnabled(False)
        self.NameEditBox.setObjectName("NameEditBox")
        self.ConfirmPassword_Label = QtWidgets.QLabel(self.centralwidget)
        self.ConfirmPassword_Label.setGeometry(QtCore.QRect(391, 390, 171, 24))
        self.ConfirmPassword_Label.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ConfirmPassword_Label.setFont(font)
        self.ConfirmPassword_Label.setObjectName("ConfirmPassword_Label")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(550, 390, 21, 16))
        self.label_12.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_12.setObjectName("label_12")
        self.Password2EditBox = QtWidgets.QLineEdit(self.centralwidget)
        self.Password2EditBox.setGeometry(QtCore.QRect(390, 430, 221, 31))
        self.Password2EditBox.setAcceptDrops(True)
        self.Password2EditBox.setAutoFillBackground(False)
        self.Password2EditBox.setStyleSheet("QLineEdit{\n"
"    background: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"    border:1px solid\n"
"}\n"
"QLineEdit:focus{\n"
"    background: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"    border:1px solid #aa4f47\n"
"}\n"
"")
        self.Password2EditBox.setFrame(True)
        self.Password2EditBox.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password2EditBox.setClearButtonEnabled(False)
        self.Password2EditBox.setObjectName("Password2EditBox")
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(260, 560, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backButton.setFont(font)
        self.backButton.setAcceptDrops(False)
        self.backButton.setStyleSheet("QPushButton{    \n"
"    background-color: rgb(235, 255, 251);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgb(246, 255, 225);\n"
"}\n"
"")
        self.backButton.setText("")
        BackIcon=path.join(base_dir, "BackIcon.png")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(BackIcon), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backButton.setIcon(icon1)
        self.backButton.setIconSize(QtCore.QSize(40, 40))
        self.backButton.setCheckable(False)
        self.backButton.setFlat(False)
        self.backButton.setObjectName("backButton")
        self.ErrorMessage_label = QtWidgets.QLabel(self.centralwidget)
        self.ErrorMessage_label.setGeometry(QtCore.QRect(320, 550, 351, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ErrorMessage_label.setFont(font)
        self.ErrorMessage_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ErrorMessage_label.setStyleSheet("color: rgb(255, 0, 0);")
        self.ErrorMessage_label.setText("")
        self.ErrorMessage_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ErrorMessage_label.setObjectName("ErrorMessage_label")
        self.Welcome_Label.raise_()
        self.Email_Label.raise_()
        self.Password_Label.raise_()
        self.EmailEditBox.raise_()
        self.Password1EditBox.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.RegisterButton.raise_()
        self.label_9.raise_()
        self.OptiVision_Image.raise_()
        self.Name_Label.raise_()
        self.label_10.raise_()
        self.NameEditBox.raise_()
        self.ConfirmPassword_Label.raise_()
        self.label_12.raise_()
        self.Password2EditBox.raise_()
        self.backButton.raise_()
        self.ErrorMessage_label.raise_()
        OptiVision.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OptiVision)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 852, 26))
        self.menubar.setObjectName("menubar")
        OptiVision.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OptiVision)
        self.statusbar.setObjectName("statusbar")
        OptiVision.setStatusBar(self.statusbar)

        self.retranslateUi(OptiVision)
        QtCore.QMetaObject.connectSlotsByName(OptiVision)
        
        OptiVision.setTabOrder(self.NameEditBox,self.EmailEditBox)
        OptiVision.setTabOrder(self.EmailEditBox,self.Password1EditBox)
        OptiVision.setTabOrder(self.Password1EditBox,self.Password2EditBox)
        OptiVision.setTabOrder(self.Password2EditBox,self.RegisterButton)
    def retranslateUi(self, OptiVision):
        _translate = QtCore.QCoreApplication.translate
        OptiVision.setWindowTitle(_translate("OptiVision", "OptiVision"))
        self.Welcome_Label.setText(_translate("OptiVision", "Register:"))
        self.Email_Label.setText(_translate("OptiVision", "Email:"))
        self.Password_Label.setText(_translate("OptiVision", "Password:"))
        self.label_5.setText(_translate("OptiVision", "*"))
        self.label_6.setText(_translate("OptiVision", "*"))
        self.RegisterButton.setText(_translate("OptiVision", "Register"))
        self.Name_Label.setText(_translate("OptiVision", "Name:"))
        self.label_10.setText(_translate("OptiVision", "*"))
        self.ConfirmPassword_Label.setText(_translate("OptiVision", "Confirm Password"))
        self.label_12.setText(_translate("OptiVision", "*"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OptiVision = QtWidgets.QMainWindow()
    ui = Ui_Register()
    ui.setupUi(OptiVision)
    OptiVision.show()
    sys.exit(app.exec_())
